// <auto-generated />
using System;
using GmintaDocs.AdminDirectorios.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GmintaDocs.AdminDirectorios.Infrastructure.Migrations
{
    [DbContext(typeof(AdminDirectoriosDbContext))]
    [Migration("20260626040850_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmintaDocs.AdminDirectorios.Domain.Directorio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_directorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdDirectorioPadre")
                        .HasColumnType("bigint")
                        .HasColumnName("id_directorio_padre");

                    b.Property<long?>("IdDirectorioV10")
                        .HasColumnType("bigint")
                        .HasColumnName("id_directorio_v10");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("directorios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
