// <auto-generated />
using System;
using GmintaDocs.AdminFormularios.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GmintaDocs.AdminFormularios.Infrastructure.Migrations
{
    [DbContext(typeof(AdminFormulariosDbContext))]
    partial class AdminFormulariosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmintaDocs.AdminFormularios.Domain.Campo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_campo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Campo1")
                        .HasColumnType("text")
                        .HasColumnName("campo1");

                    b.Property<string>("Campo2")
                        .HasColumnType("text")
                        .HasColumnName("campo2");

                    b.Property<string>("CascadaDe")
                        .HasColumnType("text")
                        .HasColumnName("cascada_de");

                    b.Property<string>("Columna")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("columna");

                    b.Property<short>("Control")
                        .HasColumnType("smallint")
                        .HasColumnName("control");

                    b.Property<short?>("Enlace")
                        .HasColumnType("smallint")
                        .HasColumnName("enlace");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long?>("IdEnlace")
                        .HasColumnType("bigint")
                        .HasColumnName("id_enlace");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<int>("LongDato")
                        .HasColumnType("integer")
                        .HasColumnName("long_dato");

                    b.Property<string>("Mascara")
                        .HasColumnType("text")
                        .HasColumnName("mascara");

                    b.Property<bool>("Mostrar")
                        .HasColumnType("boolean")
                        .HasColumnName("mostrar");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<bool>("Requerido")
                        .HasColumnType("boolean")
                        .HasColumnName("requerido");

                    b.Property<bool>("Sticker")
                        .HasColumnType("boolean")
                        .HasColumnName("sticker");

                    b.Property<short>("TipoDato")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_dato");

                    b.Property<bool>("Unico")
                        .HasColumnType("boolean")
                        .HasColumnName("unico");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("campos", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.AdminFormularios.Domain.Copia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdDirectorio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_directorio");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("copias", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.AdminFormularios.Domain.Formulario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdPadre")
                        .HasColumnType("bigint")
                        .HasColumnName("id_padre");

                    b.Property<bool>("Imagen")
                        .HasColumnType("boolean")
                        .HasColumnName("imagen");

                    b.Property<short>("LongRadicado")
                        .HasColumnType("smallint")
                        .HasColumnName("long_radicado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tabla");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("formularios", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.AdminFormularios.Domain.ItemLista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdItemPadre")
                        .HasColumnType("bigint")
                        .HasColumnName("id_item_padre");

                    b.Property<long>("IdLista")
                        .HasColumnType("bigint")
                        .HasColumnName("id_lista");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("item_lista", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.AdminFormularios.Domain.Lista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_lista");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdListaPadre")
                        .HasColumnType("bigint")
                        .HasColumnName("id_lista_padre");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("lista", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.AdminFormularios.Domain.MensajeNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("mensajes_notificacion", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.AdminFormularios.Domain.ParametroMensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_parametro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("campo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<int>("IdPlantilla")
                        .HasColumnType("integer")
                        .HasColumnName("id_plantilla");

                    b.Property<string>("Parametro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parametro");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tabla");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("parametros_mensaje", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
