// <auto-generated />
using System;
using GmintaDocs.Tareas.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GmintaDocs.Tareas.Infrastructure.Migrations
{
    [DbContext(typeof(TareasDbContext))]
    partial class TareasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmintaDocs.Tareas.Domain.Agenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Comienza")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("comienza");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("EsTodoDia")
                        .HasColumnType("boolean")
                        .HasColumnName("es_todo_dia");

                    b.Property<string>("ExcepcionRecurrencia")
                        .HasColumnType("text")
                        .HasColumnName("excepcion_recurrencia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("Finaliza")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finaliza");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("ReglaRecurrencia")
                        .HasColumnType("text")
                        .HasColumnName("regla_recurrencia");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("agenda", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Tareas.Domain.CarpetaTarea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("Padre")
                        .HasColumnType("smallint")
                        .HasColumnName("padre");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("carpeta_tarea", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Tareas.Domain.ComentarioTarea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("autor");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdTarea")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tarea");

                    b.Property<long>("IdWorkflow")
                        .HasColumnType("bigint")
                        .HasColumnName("id_workflow");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("comentarios_tarea", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Tareas.Domain.ContenidoCarpeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("IdCarpetaTarea")
                        .HasColumnType("bigint")
                        .HasColumnName("id_carpeta_tarea");

                    b.Property<long>("IdTarea")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tarea");

                    b.HasKey("Id");

                    b.ToTable("contenido_carpeta", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Tareas.Domain.LoteWf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_lote");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<int>("IdPaso")
                        .HasColumnType("integer")
                        .HasColumnName("id_paso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsable");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("lote_wf", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Tareas.Domain.Tarea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tarea");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asunto");

                    b.Property<bool>("Aviso")
                        .HasColumnType("boolean")
                        .HasColumnName("aviso");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Dias")
                        .HasColumnType("integer")
                        .HasColumnName("dias");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaAviso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aviso");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ejecucion");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recepcion");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("Horas")
                        .HasColumnType("integer")
                        .HasColumnName("horas");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdWorkflow")
                        .HasColumnType("bigint")
                        .HasColumnName("id_workflow");

                    b.Property<int>("Minutos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos");

                    b.Property<int>("Paso")
                        .HasColumnType("integer")
                        .HasColumnName("paso");

                    b.Property<int>("PasoDestino")
                        .HasColumnType("integer")
                        .HasColumnName("paso_destino");

                    b.Property<int>("PasoSiguiente")
                        .HasColumnType("integer")
                        .HasColumnName("paso_siguiente");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prioridad");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remitente");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsable");

                    b.Property<string>("ResponsablePasoSiguiente")
                        .HasColumnType("text")
                        .HasColumnName("responsable_paso_siguiente");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("tareas", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Tareas.Domain.TareaLote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdLote")
                        .HasColumnType("bigint")
                        .HasColumnName("id_lote");

                    b.Property<long>("IdTarea")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tarea");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("tareas_lote", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
