// <auto-generated />
using System;
using GmintaDocs.Workflow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GmintaDocs.Workflow.Infrastructure.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmintaDocs.Workflow.Domain.ConfiguracionPaso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<int>("IdOpcion")
                        .HasColumnType("integer")
                        .HasColumnName("id_opcion");

                    b.Property<int>("IdPaso")
                        .HasColumnType("integer")
                        .HasColumnName("id_paso");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("configuracion_paso", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Workflow.Domain.Evidencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("DocumentoHtml")
                        .HasColumnType("text")
                        .HasColumnName("documento_html");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<int>("IdOpcion")
                        .HasColumnType("integer")
                        .HasColumnName("id_opcion");

                    b.Property<long>("IdTarea")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tarea");

                    b.Property<string>("IdTransaccion")
                        .HasColumnType("text")
                        .HasColumnName("id_transaccion");

                    b.Property<long>("IdWorkflow")
                        .HasColumnType("bigint")
                        .HasColumnName("id_workflow");

                    b.Property<string>("NombreEvidencia")
                        .HasColumnType("text")
                        .HasColumnName("nombre_evidencia");

                    b.Property<string>("Parametros")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parametros");

                    b.Property<bool>("Procesado")
                        .HasColumnType("boolean")
                        .HasColumnName("procesado");

                    b.Property<string>("RespuestaJson")
                        .HasColumnType("text")
                        .HasColumnName("respuesta_json");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("evidencias", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Workflow.Domain.FormularioWorkflow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<long>("IdRegistro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro");

                    b.Property<long>("IdWorkflow")
                        .HasColumnType("bigint")
                        .HasColumnName("id_workflow");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("formulario_workflow", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Workflow.Domain.GrupoWf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("grupos_wf", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Workflow.Domain.MiembroGrupoWf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    b.Property<string>("Miembro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("miembro");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("miembros_grupo_wf", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Workflow.Domain.Paso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer")
                        .HasColumnName("id_proceso");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("paso");

                    b.Property<int>("Plazo")
                        .HasColumnType("integer")
                        .HasColumnName("plazo");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prioridad");

                    b.Property<string>("UnidadPlazo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unidad_plazo");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("paso", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Workflow.Domain.PosiblePasoDevolucion", b =>
                {
                    b.Property<int>("Paso")
                        .HasColumnType("integer")
                        .HasColumnName("paso");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer")
                        .HasColumnName("id_proceso");

                    b.HasKey("Paso", "Descripcion", "IdProceso");

                    b.ToTable("posibles_pasos_devolucion", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Workflow.Domain.Proceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_proceso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("proceso", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.Workflow.Domain.Workflow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_workflow");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer")
                        .HasColumnName("id_proceso");

                    b.Property<long>("IdRegistro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro");

                    b.Property<long?>("IdWorkflowV10")
                        .HasColumnType("bigint")
                        .HasColumnName("id_workflow_v10");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.Property<string>("WorkflowV10")
                        .HasColumnType("text")
                        .HasColumnName("workflow_v10");

                    b.HasKey("Id");

                    b.ToTable("workflow", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
