// <auto-generated />
using System;
using GmintaDocs.GestionDocumental.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GmintaDocs.GestionDocumental.Infrastructure.Migrations
{
    [DbContext(typeof(GestionDocumentalDbContext))]
    partial class GestionDocumentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmintaDocs.GestionDocumental.Domain.Archivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_archivo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Directorio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("directorio");

                    b.Property<bool>("EsVersionActual")
                        .HasColumnType("boolean")
                        .HasColumnName("es_version_actual");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<string>("Etiquetas")
                        .HasColumnType("text")
                        .HasColumnName("etiquetas");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<DateTime>("FechaDocumento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_documento");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdArchivoPrincipal")
                        .HasColumnType("bigint")
                        .HasColumnName("id_archivo_principal");

                    b.Property<int?>("IdDirectorioV10")
                        .HasColumnType("integer")
                        .HasColumnName("id_directorio_v10");

                    b.Property<long?>("IdFormularioV10")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario_v10");

                    b.Property<long>("IdPrimeraVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_primera_version");

                    b.Property<long?>("IdRegistroArchivoV10")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro_archivo_v10");

                    b.Property<long?>("IdRegistroV10")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro_v10");

                    b.Property<long>("IdTipoDocumento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_documento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archivo");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<string>("RutaV10")
                        .HasColumnType("text")
                        .HasColumnName("ruta_v10");

                    b.Property<string>("UnidadAlmacenamiento")
                        .HasColumnType("text")
                        .HasColumnName("unidad_almacenamiento");

                    b.Property<string>("UnidadConservacion")
                        .HasColumnType("text")
                        .HasColumnName("unidad_conservacion");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("archivos", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.GestionDocumental.Domain.ArchivoFormulario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdArchivo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_archivo");

                    b.Property<long?>("IdDirectorio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_directorio");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<long>("IdRegistro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro");

                    b.Property<long?>("IdWorkflow")
                        .HasColumnType("bigint")
                        .HasColumnName("id_workflow");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("archivos_formulario", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.GestionDocumental.Domain.AyudaAlmacenar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdDirectorio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_directorio");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<long>("IdTipoDocumento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_documento");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("ayuda_almacenar", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.GestionDocumental.Domain.BusquedaArchivo", b =>
                {
                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archivo");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Directorio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("directorio");

                    b.Property<bool>("EsVersionActual")
                        .HasColumnType("boolean")
                        .HasColumnName("es_version_actual");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<string>("Etiquetas")
                        .HasColumnType("text")
                        .HasColumnName("etiquetas");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<DateTime>("FechaDocumento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_documento");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("IdArchivo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_archivo");

                    b.Property<long>("IdArchivoPrincipal")
                        .HasColumnType("bigint")
                        .HasColumnName("id_archivo_principal");

                    b.Property<long?>("IdDirectorio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_directorio");

                    b.Property<long?>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<long>("IdPrimeraVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_primera_version");

                    b.Property<long?>("IdRegistro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro");

                    b.Property<long>("IdTipoDocumento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_documento");

                    b.Property<long?>("IdWorkflow")
                        .HasColumnType("bigint")
                        .HasColumnName("id_workflow");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.ToTable("busqueda_archivos", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.GestionDocumental.Domain.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<long>("IdRegistro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tabla");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.GestionDocumental.Domain.RelacionArchivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("IdArchivo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_archivo");

                    b.Property<long>("IdRelacion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_relacion");

                    b.HasKey("Id");

                    b.ToTable("relacion_archivos", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.GestionDocumental.Domain.TipoDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_documento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<bool>("ControlaVersion")
                        .HasColumnType("boolean")
                        .HasColumnName("controla_version");

                    b.Property<bool>("ControlaVigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("controla_vigencia");

                    b.Property<int>("DiasVigencia")
                        .HasColumnType("integer")
                        .HasColumnName("dias_vigencia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("tipo_documento", (string)null);
                });

            modelBuilder.Entity("GmintaDocs.GestionDocumental.Domain.Trd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Administrativo")
                        .HasColumnType("boolean")
                        .HasColumnName("administrativo");

                    b.Property<bool>("Autentico")
                        .HasColumnType("boolean")
                        .HasColumnName("autentico");

                    b.Property<bool>("Cientifico")
                        .HasColumnType("boolean")
                        .HasColumnName("cientifico");

                    b.Property<bool>("ConservacionTotal")
                        .HasColumnType("boolean")
                        .HasColumnName("conservacion_total");

                    b.Property<bool>("Contable")
                        .HasColumnType("boolean")
                        .HasColumnName("contable");

                    b.Property<bool>("Cultural")
                        .HasColumnType("boolean")
                        .HasColumnName("cultural");

                    b.Property<bool>("Desmaterializado")
                        .HasColumnType("boolean")
                        .HasColumnName("desmaterializado");

                    b.Property<bool>("Eliminacion")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminacion");

                    b.Property<string>("EliminacionElectronica")
                        .HasColumnType("text")
                        .HasColumnName("eliminacion_electronica");

                    b.Property<bool>("EstampadoCronologico")
                        .HasColumnType("boolean")
                        .HasColumnName("estampado_cronologico");

                    b.Property<bool>("EvidenciaNiif")
                        .HasColumnType("boolean")
                        .HasColumnName("evidencia_niif");

                    b.Property<bool>("Facilitativo")
                        .HasColumnType("boolean")
                        .HasColumnName("facilitativo");

                    b.Property<bool>("Facultativo")
                        .HasColumnType("boolean")
                        .HasColumnName("facultativo");

                    b.Property<bool>("FirmaBiometrica")
                        .HasColumnType("boolean")
                        .HasColumnName("firma_biometrica");

                    b.Property<bool>("FirmaDigital")
                        .HasColumnType("boolean")
                        .HasColumnName("firma_digital");

                    b.Property<bool>("Fiscal")
                        .HasColumnType("boolean")
                        .HasColumnName("fiscal");

                    b.Property<bool>("Fisico")
                        .HasColumnType("boolean")
                        .HasColumnName("fisico");

                    b.Property<bool>("Funcional")
                        .HasColumnType("boolean")
                        .HasColumnName("funcional");

                    b.Property<bool>("Historico")
                        .HasColumnType("boolean")
                        .HasColumnName("historico");

                    b.Property<long>("IdFormulario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_formulario");

                    b.Property<long>("IdRegistro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro");

                    b.Property<long?>("IdTipoDocumental")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_documental");

                    b.Property<bool>("Inmaterializado")
                        .HasColumnType("boolean")
                        .HasColumnName("inmaterializado");

                    b.Property<bool>("Integro")
                        .HasColumnType("boolean")
                        .HasColumnName("integro");

                    b.Property<bool>("Legal")
                        .HasColumnType("boolean")
                        .HasColumnName("legal");

                    b.Property<bool>("Ley1581")
                        .HasColumnType("boolean")
                        .HasColumnName("ley1581");

                    b.Property<bool>("Microfilmacion")
                        .HasColumnType("boolean")
                        .HasColumnName("microfilmacion");

                    b.Property<bool>("Misional")
                        .HasColumnType("boolean")
                        .HasColumnName("misional");

                    b.Property<string>("NivelSeguridad")
                        .HasColumnType("text")
                        .HasColumnName("nivel_seguridad");

                    b.Property<string>("Normatividad")
                        .HasColumnType("text")
                        .HasColumnName("normatividad");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<bool>("PerteneceSgc")
                        .HasColumnType("boolean")
                        .HasColumnName("pertenece_sgc");

                    b.Property<float?>("PorcentajeSeleccion")
                        .HasColumnType("real")
                        .HasColumnName("porcentaje_seleccion");

                    b.Property<string>("Procedimiento")
                        .HasColumnType("text")
                        .HasColumnName("procedimiento");

                    b.Property<float?>("RetencionAc")
                        .HasColumnType("real")
                        .HasColumnName("retencion_ac");

                    b.Property<float?>("RetencionAg")
                        .HasColumnType("real")
                        .HasColumnName("retencion_ag");

                    b.Property<float?>("RetencionElectronica")
                        .HasColumnType("real")
                        .HasColumnName("retencion_electronica");

                    b.Property<string>("Seguridad")
                        .HasColumnType("text")
                        .HasColumnName("seguridad");

                    b.Property<bool>("Seleccion")
                        .HasColumnType("boolean")
                        .HasColumnName("seleccion");

                    b.Property<bool>("Simple")
                        .HasColumnType("boolean")
                        .HasColumnName("simple");

                    b.Property<bool>("Sustantivo")
                        .HasColumnType("boolean")
                        .HasColumnName("sustantivo");

                    b.HasKey("Id");

                    b.ToTable("trd", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
